# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160919_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureToggling',
            new_name='FeatureToggle',
        ),
    ]
