# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160919_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
