# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:01
from __future__ import unicode_literals

import core.methods
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160919_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=core.methods.school_logo_upload_path_handler)),
                ('name', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
