# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160920_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address_ptr',
        ),
        migrations.AddField(
            model_name='school',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='post_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.AUState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='street',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='suburb',
            field=models.CharField(default=None, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='post_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.AUState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='street',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='suburb',
            field=models.CharField(default=None, max_length=75),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
