# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_austate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='school',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='state',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
