# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_unit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='code',
            new_name='name',
        ),
    ]
